domainFilters:
- ${domain}
sources:
- ingress
txtOwnerId: ${clusterName}
provider: google
google:
  project: ${projectId}
  zoneVisibility: ${zoneVisibility}
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: ${serviceAccount}
